# Generated by Django 3.0.5 on 2020-05-03 03:34

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='')),
                ('title', models.TextField()),
                ('story', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RAGP_Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', image_optimizer.fields.OptimizedImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('story', models.TextField()),
            ],
        ),
    ]
